### PR TITLE
Closes issue #784: Avoid losing meta job information after successful finish.

### LINKED ISSUE #784: Worker.handle_job_success overwrites job meta information
When a job completes successfully, its `meta` dictionary is overwritten with old values. The use case:

1. When a job is queued, it's done with `meta={'progress: 'Queued'}`.
2. When a job is started, the work function updates with `job.meta['progress'] = 'Started'; job.save()`
3. As the job progresses, its `meta['progress']` info is updated with progress information in the same way.
4. The job completes, and at that point the job on Redis has some value of `meta['progress']` which indicates how far it had progressed.
5. `Worker.handle_job_success` is called with an in-memory copy of the job which has the original progress value of `Queued`. It saves this job instance with an updated status of `finished`, but *omits  to preserve the meta data* before doing this. As a result, the job's `meta` dict is overwritten with the original `{progress: Queued}` value, overwriting any other information in the meta dict.

IMO `Worker.handle_job_success` should get the job's `meta` data and restore it while saving the updated status. See pull request #785 for a fix.

### PR DESCRIPTION
**Pull request by vsajip**
As described in the issue.

### CODE REVIEW

**Comment by vsajip** [comment]
Tests failing, needs more work.

**Comment by vsajip** [comment]
Test is failing on PyPy, but appears unrelated to this change.

**Comment by WeatherGod** [comment]
I think my PR #781 solves the same problem in a simpler way?

**Comment by WeatherGod** [comment]
In addition, this PR doesn't protect against the same clobbering if the job fails

**Comment by vsajip** [comment]
> I think my PR #781 solves the same problem in a simpler way?

Sorry @WeatherGod, I didn't spot your PR before creating mine.

Initially, I tried just adding a `job.refresh()` in `handle_job_success()`, but that caused the `result` to be overwritten and lost. Looks like I just put the `refresh()` in the wrong place.

> In addition, this PR doesn't protect against the same clobbering if the job fails

That's true, too. And you've covered the failure case in the tests, too. So I think I'll close my PR in favour of yours! Nice one.

**Pull request closed without merging**
