### PR TITLE
send heartbeat during supsension check

### PR DESCRIPTION
**Pull request by red-crown**
Have workers continue to send heartbeat during suspension check loop. #804

### CODE REVIEW

**Comment by selwin** [comment]
Do you mind modifying check_for_suspension() and heartbeat() so they can both be done with Redis pipeline?

**Comment by red-crown** [comment]
sure

**Comment by red-crown** [comment]
Why do we want to make it work with redis pipeline? Inside check_for_suspension() the new call to heartbeat() is the only place it makes sense.  The internal calls to is_suspended() which is called every second and set_state() need a non-pipeline connection. Also, the only call to check_for_suspension() is within work() which does not accept a pipeline.

Is this for external user calls to check_for_suspension() or is the idea to basically make the heartbeat() call within the suspension check loop "optional"?

**Comment by selwin** [comment]
You're right, it doesn't make sense for `check_for_suspension()` to support `pipeline`.

What I wanted to achieve is for RQ to be able to check whether RQ is suspended and sending `heartbeat ` in one single Redis call (instead of two) to make it more efficient, since this will be done every second.

Looking at the code, I think we can accomplish this by:
1. Modifying `is_suspended(connection, worker)` to accept `worker` argument
2. `worker.heartbeat()` already accepts `pipeline` argument

**Comment by selwin** [comment]
@red-crown I plan on releasing a new version at the end of this month. Would be great if we can get this PR in before then.

**Comment by red-crown** [comment]
Sure thing. Will work on it tonight.

**Comment by selwin** [comment]
@red-crown gentle reminder to update this PR 😀

**Comment by selwin** [comment]
@red-crown ping :)

**Comment by theodesp** [comment]
Is it ok if I push a PR for this? 
What I've done is I've followed this list:
```
  - Modifying is_suspended(connection, worker) to accept worker argument
  - worker.heartbeat() already accepts pipeline argument
```
And added the request in a pipeline.

What I need is to add tests for coverage

**Comment by selwin** [comment]
@theodesp yes, please submit a new PR for this if you can :)

**Pull request closed without merging**
