### PR TITLE
ZADD bugfix

### LINKED ISSUE #498: ZADD command failurs with related tasks
Redis and StrictRedis have different interface of zadd function. See https://redis-py.readthedocs.org/en/latest/index.html#redis.Redis.zadd and https://redis-py.readthedocs.org/en/latest/index.html#redis.StrictRedis.zadd

Bug in https://github.com/nvie/rq/blob/0.5.0/rq/registry.py#L31.
Playback script:

    # workers.py
    from time import sleep
    
    def wait():
        sleep(2)
    return 1

    # main.py
    from redis import Redis
    from rq import Queue
    from workers import wait

    q = Queue(connection=Redis())
    j1 = q.enqueue(wait)
    j2 = q.enqueue(wait, depends_on=j1)

Error:

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python3.4/dist-packages/rq/queue.py", line 249, in enqueue
        job_id=job_id, at_front=at_front)
      File "/usr/local/lib/python3.4/dist-packages/rq/queue.py", line 203, in enqueue_call
        job.register_dependency(pipeline=pipe)
      File "/usr/local/lib/python3.4/dist-packages/rq/job.py", line 553, in register_dependency
        registry.add(self, pipeline=pipeline)
      File "/usr/local/lib/python3.4/dist-packages/rq/registry.py", line 31, in add
        return pipeline.zadd(self.key, score, job.id)
      File "/usr/local/lib/python3.4/dist-packages/redis/client.py", line 2025, in zadd
        return self.execute_command('ZADD', name, *pieces)
      File "/usr/local/lib/python3.4/dist-packages/redis/client.py", line 2395, in execute_command
        return self.immediate_execute_command(*args, **kwargs)
      File "/usr/local/lib/python3.4/dist-packages/redis/client.py", line 2414, in immediate_execute_command
        return self.parse_response(conn, command_name, **options)
      File "/usr/local/lib/python3.4/dist-packages/redis/client.py", line 2537, in parse_response
        self, connection, command_name, **options)
      File "/usr/local/lib/python3.4/dist-packages/redis/client.py", line 577, in parse_response
        response = connection.read_response()
      File "/usr/local/lib/python3.4/dist-packages/redis/connection.py", line 574, in read_response
        raise response
    redis.exceptions.ResponseError: value is not a valid float

### PR DESCRIPTION
**Pull request by vladkens**
Fixed #498

### CODE REVIEW

**Comment by selwin** [comment]
Thanks for the PR! Do you mind adding a test case for this?

**Comment by vladkens** [comment]
Yes, will soon send.

**Comment by nvie** [comment]
I don't mind a lacking test case for this. What would this be testing anyway? Thanks for the fix.

**Comment by selwin** [comment]
Simply passing in Redis/StrictRedis connection to make sure it doesn't raise an error. No worries, thanks for the PR and merge!

**Pull request merged**
