### PR TITLE
Cancel and Delete differences

### PR DESCRIPTION
**Pull request by glaslos**
This addresses the differences between job.cancel() and job.delete() see discussion in #362 and especially https://github.com/nvie/rq/issues/362#issuecomment-49991135

### CODE REVIEW

**Comment by glaslos** [comment]
We might want to discuss handling of depending jobs (see #427) as it has changed a bit.

**Comment by selwin** [comment]
Will take a closer look at this when I have the time

**Comment by selwin** [comment]
Sorry I haven't gotten around to reviewing this. I'll try to do it tomorrow!

**Comment by selwin** [comment]
Thanks!

**Pull request merged**
