### PR TITLE
triggering shutdown by setting a redis flag

### PR DESCRIPTION
**Pull request by jtushman**
**Problem Statement**
We use rq on heroku and their way to the shutdown the worker that runs rq does not ensure a safe shutdown.
   
From Heroku docs:  https://devcenter.heroku.com/articles/dynos
```
When a worker is stoped by ps:scaling or pushing out a new release or any heroku operation.
The dyno manager sends the working SIGTERM

The process then has 10 seconds to shut down gracefully.

If the process is still alive -- then SIGKILL is then sent
```

So if a job takes more then 10 secs (which many of our jobs do) -- we are going to be out of luck.  The job will be killed in a potentially unsafe point

So we needed an approach where we could set a flag on redis, that the rq worker can ping.

I introduced the key:  'rq:worker:pause_work'  Which any process can set.  If the worker sees that it has been set -- it hops into a pause loop, until the key is deleted.

In Worker#work at the top of the `while True:` block

``` python
    try:
        before_state = None
        notified = False

        while Worker.paused() and not self.stopped:

            if burst:
                self.log.warn('Paused in burst mode -- exiting.')
                self.log.warn('Note:  There could still be unperformed jobs on the queue')
                raise StopRequested

            if not notified:
                self.log.warn('Stopping on pause request REALLY.')
                before_state = self.get_state()
                self.set_state('paused')
                notified = True
            time.sleep(1)
    except StopRequested:
        break
```

### CODE REVIEW

**Comment by jtushman** [comment]
Happy New Year @nvie, @selwin!  I am back from break -- lemme know if this needs any more polish

**Comment by selwin** [comment]
I'm going to merge this in. Thanks a lot for your hardwork @jtushman !

**Comment by jtushman** [comment]
Woot!

**Comment by dfrankow** [comment]
I see that this was merged in, including into the rq command-line client ("rq suspend" and "rq resume").

But how exactly should this be used for people running on heroku? Are there any docs?

**Pull request merged**
