### PR TITLE
Worker accepts custom queue class

### PR DESCRIPTION
**Pull request by antoineleclair**
Otherwise I had to do something like:
```python
worker = Worker(queues)
worker.queue_class = CustomQueueClass
worker.work()
```

With this pull request, it's now possible to do:
```python
worker = Worker(queues, queue_class=CustomQueueClass)
worker.work()
```

Also, before this pull request, passing the queue class in the command line would not work as expected.

### CODE REVIEW

**Comment by selwin** [comment]
This is a nice PR. Do you mind documenting this so other people can easily discover this feature?

**Comment by selwin** [comment]
@antoineleclair could you please resolve the conflicts so I can merge this PR in?

**Comment by antoineleclair** [comment]
@selwin There you go.

**Comment by selwin** [comment]
Thanks!

**Pull request merged**
