### PR TITLE
log job result in DEBUG level and truncate to 2k symbols

### PR DESCRIPTION
**Pull request by tbaugis**
I think it makes sense moving output to DEBUG as you'd care about it in logs only while debugging. Over certain size the output in logs also gets quite unwieldy, so truncating it to 2k chars.

Keep up the good work and let me know if things should be done differently!

### CODE REVIEW

**Comment by selwin** [comment]
@tbaugis thanks for the PR!

I like the logging level changes but this is not the right place to truncate logging output. Truncating output should on the logging formatter level. If we truncate the output at this level, you won't be able to log the whole output even if you wanted to.

**Comment by tbaugis** [comment]
I see, thanks for getting back!

Would you mind simply changing the log level to DEBUG then, or should i make a one-liner pull request?

**Comment by selwin** [comment]
Please keep the current code you have now, but don't truncate the result to 2k characters :). So `Job Ok` will still be logged on `info`, but the `result` will be only be logged on `debug`.

**Comment by tbaugis** [comment]
updated as asked!

**Comment by selwin** [comment]
Thanks!

**Pull request merged**
