### PR TITLE
Job delete should delete from StartedJobRegistry

### PR DESCRIPTION
**Pull request by olingerc**
First draft. I am no longer 100% sure about this, since deleting the job still leaves it on the worker until it has finished executing, so technically it still has been started. On the other hand, we delete the redis hash from rq:jobs so this should be fine also?

### CODE REVIEW

**Comment by olingerc** [comment]
Refers to #632

**Comment by olingerc** [comment]
Hmmm... Hold off on this for now, my tests this morning fail. Don't code at night without coffee ;-)

**Comment by olingerc** [comment]
I updated the PR to resolve conflicts and use connection instead of pipeline. I also added a test case.
@selwin. Does updating the PR automatically generate a message to you oris it better to specifically add a comment?

**Comment by selwin** [comment]
Sorry for the super late reply.

I agree with your assessment that allowing the user to delete a running job is probably not a good idea. Perhaps we should throw an exception with a descriptive error message if the job is still running. If the user still wants to delete this, he'd need to first stop/kill the job before deleting it.

**Comment by selwin** [comment]
Ping @olingerc :)

**Comment by selwin** [comment]
Fixed in https://github.com/nvie/rq/pull/810

**Pull request closed without merging**
