### PR TITLE
add python 3.5

### PR DESCRIPTION
**Pull request by samuelcolvin**

### CODE REVIEW

**Comment by proofit404** [comment]
Can you correct pip issue first?

**Comment by samuelcolvin** [comment]
Of course, this was just a first commit to see what failed. I was working on another pull request while this built. Do all pull requests have to be completed in 15 minutes?

**Comment by samuelcolvin** [comment]
ready AFAIK.

**Comment by proofit404** [comment]
Thanks :)

**Comment by samuelcolvin** [comment]
`--use-mirrors` is depreciated anyway so I really can't see a problem with merging this.

**Comment by nvie** [comment]
Thanks!

**Pull request merged**
